module.exports = {
  apps: [
    {
      name: 'visheart-backend',
      cwd: '/app/backend',
      script: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      error_file: '/app/logs/backend-error.log',
      out_file: '/app/logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
      env: {
        NODE_ENV: process.env.NODE_ENV || 'development',
        HOST: process.env.HOST || '0.0.0.0',
        PORT: process.env.PORT || '5000',
        MONGODB_URI: process.env.MONGODB_URI,
        REDIS_HOST: process.env.REDIS_HOST,
        REDIS_PORT: process.env.REDIS_PORT,
        SESSION_SECRET: process.env.SESSION_SECRET,
        SESSION_NAME: process.env.SESSION_NAME,
        SESSION_MAX_AGE: process.env.SESSION_MAX_AGE,
        STORAGE_MODE: process.env.STORAGE_MODE,
        AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
        AWS_REGION: process.env.AWS_REGION,
        AWS_ACCESS_KEY_ID: process.env.AWS_ACCESS_KEY_ID,
        AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
        S3_ENDPOINT: process.env.S3_ENDPOINT,
        S3_ACCESS_KEY_ID: process.env.S3_ACCESS_KEY_ID,
        S3_SECRET_ACCESS_KEY: process.env.S3_SECRET_ACCESS_KEY,
        S3_FORCE_PATH_STYLE: process.env.S3_FORCE_PATH_STYLE,
        GPU_API_URL: process.env.GPU_API_URL,
        GPU_JWT_SECRET: process.env.GPU_JWT_SECRET,
        GPU_SERVER_URL: process.env.GPU_SERVER_URL,
        GPU_SERVER_PORT: process.env.GPU_SERVER_PORT,
        GPU_SERVER_SSL: process.env.GPU_SERVER_SSL,
        GPU_SERVER_AUTH_JWT_SECRET: process.env.GPU_SERVER_AUTH_JWT_SECRET,
        GPU_SERVER_ID_FOR_GPU_SERVER: process.env.GPU_SERVER_ID_FOR_GPU_SERVER,
        GPU_SERVER_IDENTITY: process.env.GPU_SERVER_IDENTITY,
        GPU_SERVER_JWT_REFRESH_INTERVAL: process.env.GPU_SERVER_JWT_REFRESH_INTERVAL,
        GPU_SERVER_JWT_LIFETIME_SECONDS: process.env.GPU_SERVER_JWT_LIFETIME_SECONDS,
        CALLBACK_URL: process.env.CALLBACK_URL,
      },
    },
    {
      name: 'visheart-frontend',
      cwd: '/app/frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      instances: 1,
      exec_mode: 'fork',
      error_file: '/app/logs/frontend-error.log',
      out_file: '/app/logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 4000,
      env: {
        NODE_ENV: process.env.NODE_ENV || 'development',
        NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL,
        NEXT_PUBLIC_ENV: process.env.NEXT_PUBLIC_ENV,
      },
    },
  ],
};
