allowBuilds:
  bcrypt: set this to true or false
  core-js: set this to true or false
  mongodb-memory-server: set this to true or false
  unrs-resolver: set this to true or false
onlyBuiltDependencies:
  - bcrypt
  - mongodb-memory-server
  - unrs-resolver
