// File: src/routes/alb_metrics.ts
// Description: Routes for fetching ALB (Application Load Balancer) metrics from CloudWatch

import express, { Request, Response } from 'express';
import {
    getALBRequestCountMetrics,
    getALBTargetResponseTimeMetrics,
    getALBHTTP4XXELBMetrics,
    getALBHTTP4XXTargetMetrics,
    getALBHealthyHostCountMetrics,
    getALBUnhealthyHostCountMetrics
} from '../services/cloudwatch';
import logger from '../services/logger';

const router = express.Router();
const routeLocation = 'ALB-Metrics-Routes';

// Helper function to handle ALB metric requests with consistent error handling
const handleALBMetricRequest = async (
    req: Request,
    res: Response,
    metricName: string,
    fetchFunction: () => Promise<{ timestamps: string[]; values: number[] }>
): Promise<void> => {
    try {
        logger.info(`${routeLocation}: Fetching ${metricName} metrics for ALB`);

        // Fetch metric data from CloudWatch
        const metricData = await fetchFunction();

        logger.info(`${routeLocation}: Successfully retrieved ${metricData.values.length} ${metricName} datapoints`);

        // Return the metrics in the requested format
        res.status(200).json({
            timestamps: metricData.timestamps,
            values: metricData.values,
        });

    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
        logger.error(`${routeLocation}: Failed to fetch ${metricName} metrics: ${errorMessage}`);

        // Handle specific AWS errors
        if (errorMessage.includes('ALB_NAME environment variable is not set')) {
            res.status(500).json({
                error: 'Configuration Error',
                message: 'ALB_NAME environment variable is not configured',
            });
        } else if (errorMessage.includes('AccessDenied')) {
            res.status(403).json({
                error: 'Access Denied',
                message: 'You do not have permission to access ALB CloudWatch metrics',
            });
        } else if (errorMessage.includes('InvalidParameterValue')) {
            res.status(400).json({
                error: 'Invalid Parameter',
                message: 'The ALB name or metric parameters are invalid',
            });
        } else {
            res.status(500).json({
                error: 'Internal Server Error',
                message: `Failed to retrieve ${metricName} metrics: ${errorMessage}`,
            });
        }
    }
};

/**
 * GET /metrics/alb/request-count
 * Fetches the total number of requests handled by the Application Load Balancer
 * @returns {timestamps: string[], values: number[]} - Request count data over time
 */
router.get('/request-count', async (req: Request, res: Response): Promise<void> => {
    await handleALBMetricRequest(req, res, 'ALB Request Count', getALBRequestCountMetrics);
});

/**
 * GET /metrics/alb/target-response-time
 * Fetches the average time taken by targets to respond to requests (in seconds)
 * @returns {timestamps: string[], values: number[]} - Target response time data over time
 */
router.get('/target-response-time', async (req: Request, res: Response): Promise<void> => {
    await handleALBMetricRequest(req, res, 'ALB Target Response Time', getALBTargetResponseTimeMetrics);
});

/**
 * GET /metrics/alb/http-4xx-elb
 * Fetches the number of HTTP 4xx errors generated by the Application Load Balancer itself
 * @returns {timestamps: string[], values: number[]} - ELB 4xx error count data over time
 */
router.get('/http-4xx-elb', async (req: Request, res: Response): Promise<void> => {
    await handleALBMetricRequest(req, res, 'ALB HTTP 4XX ELB Errors', getALBHTTP4XXELBMetrics);
});

/**
 * GET /metrics/alb/http-4xx-target
 * Fetches the number of HTTP 4xx errors returned by the targets behind the ALB
 * @returns {timestamps: string[], values: number[]} - Target 4xx error count data over time
 */
router.get('/http-4xx-target', async (req: Request, res: Response): Promise<void> => {
    await handleALBMetricRequest(req, res, 'ALB HTTP 4XX Target Errors', getALBHTTP4XXTargetMetrics);
});

/**
 * GET /metrics/alb/healthy-hosts
 * Fetches the number of healthy targets registered to the Application Load Balancer
 * @returns {timestamps: string[], values: number[]} - Healthy host count data over time
 */
router.get('/healthy-hosts', async (req: Request, res: Response): Promise<void> => {
    await handleALBMetricRequest(req, res, 'ALB Healthy Host Count', getALBHealthyHostCountMetrics);
});

/**
 * GET /metrics/alb/unhealthy-hosts
 * Fetches the number of unhealthy targets registered to the Application Load Balancer
 * @returns {timestamps: string[], values: number[]} - Unhealthy host count data over time
 */
router.get('/unhealthy-hosts', async (req: Request, res: Response): Promise<void> => {
    await handleALBMetricRequest(req, res, 'ALB Unhealthy Host Count', getALBUnhealthyHostCountMetrics);
});

export default router;
