"""
_test_alignment_angle_sweep.py
===============================
Read-only sweep test comparing compute_alignment_angle() (new, single-point)
against compute_alignment_angle_midpoint_LEGACY() (old, midpoint-based) from
app.bullseye_analysis, across a range of synthetic RV1/RV2 angular spreads.

This does NOT modify, monkeypatch, or reimplement either function — both are
imported and called as-is.

What this answers: is the angular offset between the two formulas' outputs a
fixed constant across RV1/RV2 geometries, or does it vary with the spread
between the two insertion points?

Usage:
    python -m app.scripts._test_alignment_angle_sweep
(run from visheart-inference-gpu/, so `app` is importable)
"""

from __future__ import annotations
import datetime
import secrets
import numpy as np

from app.bullseye_analysis import (
    compute_alignment_angle,
    compute_alignment_angle_midpoint_LEGACY,
)

# ── Run identity (for distinguishing this run from any cached/prior one) ────
RUN_TIMESTAMP = datetime.datetime.now().isoformat()
RUN_NONCE = secrets.token_hex(8)


def wrap_deg(a: float) -> float:
    """Wrap an angle in degrees to (-180, 180]."""
    return (a + 180.0) % 360.0 - 180.0


def run_sweep():
    # Fixed synthetic centroid — arbitrary, only relative geometry matters
    # since both formulas are translation-invariant w.r.t. (cx, cy).
    cx, cy = 100.0, 100.0
    radius = 40.0  # synthetic RV insertion points sit this far from centroid

    # RV1 (anterior, per Ms Kathy's convention documented in
    # compute_alignment_angle's docstring) is swept through a full circle.
    rv1_angles_deg = np.arange(0, 360, 15)  # 0, 15, ..., 345 -> 24 values

    # RV2 (inferior) spread relative to RV1 is swept from 10 deg to 170 deg
    # in 10 deg steps. (0 and 180 excluded: degenerate/coincident or
    # diametrically-opposite RV1/RV2 are not physiologically meaningful
    # configurations for this landmark pair.)
    spreads_deg = np.arange(10, 180, 10)  # 10, 20, ..., 170 -> 17 values

    rows = []
    for spread in spreads_deg:
        corrections_for_this_spread = []
        for rv1_angle in rv1_angles_deg:
            rv1_angle_rad = np.radians(rv1_angle)
            rv1 = (cx + radius * np.cos(rv1_angle_rad),
                   cy + radius * np.sin(rv1_angle_rad))

            rv2_angle_rad = np.radians(rv1_angle + spread)
            rv2 = (cx + radius * np.cos(rv2_angle_rad),
                   cy + radius * np.sin(rv2_angle_rad))

            new_angle_rad = compute_alignment_angle(cx, cy, rv1, rv2, ring_type="basal")
            legacy_angle_rad = compute_alignment_angle_midpoint_LEGACY(cx, cy, rv1, rv2)

            new_deg = np.degrees(new_angle_rad)
            legacy_deg = np.degrees(legacy_angle_rad)

            # "Required correction" = new minus legacy, wrapped to (-180, 180]
            correction_deg = wrap_deg(new_deg - legacy_deg)
            corrections_for_this_spread.append(correction_deg)

        corrections_for_this_spread = np.array(corrections_for_this_spread)
        rows.append({
            "spread_deg": int(spread),
            "correction_min_deg": float(corrections_for_this_spread.min()),
            "correction_max_deg": float(corrections_for_this_spread.max()),
            "correction_mean_deg": float(corrections_for_this_spread.mean()),
            "correction_std_deg": float(corrections_for_this_spread.std()),
            "per_rv1_angle_corrections_deg": corrections_for_this_spread.tolist(),
        })

    return rows, rv1_angles_deg


def main():
    print("=" * 100)
    print("ALIGNMENT ANGLE SWEEP TEST — compute_alignment_angle vs "
          "compute_alignment_angle_midpoint_LEGACY")
    print(f"run_timestamp = {RUN_TIMESTAMP}")
    print(f"run_nonce     = {RUN_NONCE}")
    print("=" * 100)
    print()
    print("NOTE: RV1/RV2 coordinates below are SYNTHETIC test fixtures generated by "
          "this script (points on a circle around an arbitrary centroid). They are "
          "NOT patient data.")
    print()
    print("Sweep parameters:")
    print("  RV1 angle range : 0 to 345 deg, step 15 deg (24 values, full circle)")
    print("  RV2 spread range: 10 to 170 deg relative to RV1, step 10 deg (17 values)")
    print("  centroid        : (100.0, 100.0) ; landmark radius: 40.0 px")
    print("  ring_type       : 'basal' (offset_deg = 60.0)")
    print()

    rows, rv1_angles_deg = run_sweep()

    # Full table: spread -> required correction, every tested value
    header = f"{'spread_deg':>10} | {'min_deg':>10} | {'max_deg':>10} | {'mean_deg':>10} | {'std_deg':>10}"
    print("SUMMARY TABLE (per spread, aggregated over all 24 RV1 starting angles)")
    print(header)
    print("-" * len(header))
    for row in rows:
        print(f"{row['spread_deg']:>10d} | {row['correction_min_deg']:>10.4f} | "
              f"{row['correction_max_deg']:>10.4f} | {row['correction_mean_deg']:>10.4f} | "
              f"{row['correction_std_deg']:>10.4f}")
    print()

    print("FULL TABLE — every (spread_deg, rv1_angle_deg) -> required correction (deg)")
    full_header = f"{'spread_deg':>10} | {'rv1_angle_deg':>13} | {'correction_deg':>15}"
    print(full_header)
    print("-" * len(full_header))
    for row in rows:
        for rv1_angle, corr in zip(rv1_angles_deg, row["per_rv1_angle_corrections_deg"]):
            print(f"{row['spread_deg']:>10d} | {int(rv1_angle):>13d} | {corr:>15.6f}")
    print()

    all_corrections = np.array([c for row in rows for c in row["per_rv1_angle_corrections_deg"]])
    global_min = float(all_corrections.min())
    global_max = float(all_corrections.max())
    global_range = global_max - global_min

    print("=" * 100)
    print("CONCLUSION")
    print("=" * 100)
    is_constant = global_range < 1e-6
    print(f"global min correction : {global_min:.6f} deg")
    print(f"global max correction : {global_max:.6f} deg")
    print(f"global range          : {global_range:.6f} deg")
    if is_constant:
        print("=> The required correction IS constant across the swept range "
              f"(range {global_range:.2e} deg, within floating-point tolerance).")
    else:
        print("=> The required correction is NOT constant across the swept range. "
              f"It varies by {global_range:.4f} deg (from {global_min:.4f} deg to "
              f"{global_max:.4f} deg) depending on RV1/RV2 geometry.")
    print()
    print(f"(run_timestamp={RUN_TIMESTAMP}, run_nonce={RUN_NONCE})")


if __name__ == "__main__":
    main()
